refactor: simplified fullprog_doscom.inc.nasm and fullprog_dosexe.inc.nasm, and inlined them to dosmc

diff --git a/dosmc b/dosmc
--- a/dosmc
+++ b/dosmc
@@ -96,7 +96,10 @@ OBJ2NASM_CODE='
   use integer;
   use strict;
 
-  # Basd on: https://pierrelib.pagesperso-orange.fr/exec_formats/OMF_v1.1.pdf
+  my $EXT = $ARGV[0]; my $NASMCPU = $ARGV[1];
+  die "$0: fatal: missing args\n" if @ARGV != 2;
+
+  # Based on: https://pierrelib.pagesperso-orange.fr/exec_formats/OMF_v1.1.pdf
   my $f = \*STDIN;
   my @lnames = ("-LN0");
   my @SEGMENT_ORDER = qw(_TEXT CONST CONST2 _DATA _BSS);  # Constant, OpenWatcom.
@@ -314,9 +317,89 @@ OBJ2NASM_CODE='
     $chunk_sub->($size) if $size > $i;
   }
 
-  print qq(bits 16\ncpu NASM_CPU\n);
-  print qq(%ifdef NASM_EXT_exe\n%include "fullprog_dosexe.inc.nasm"\n%else\n%include "fullprog_doscom.inc.nasm"\n%endif\n);
-  print qq(fullprog_code\n);
+  my($fullprog_code, $fullprog_data, $fullprog_bss, $fullprog_end);
+  if ($EXT eq "exe") {
+# Based on https://github.com/pts/pts-nasm-fullprog/blob/master/fullprog_dosexe.inc.nasm
+$fullprog_code = q(
+section .text align=1 vstart=-0x10
+; DOS .exe header, similar to: https://stackoverflow.com/q/14246493/97248
+exe_header:
+db 0x4d, 0x5a  ; MZ Signature.
+dw ((code_end-exe_header)+(data_end-data_start))&511  ; Image size low 9 bits.
+dw ((code_end-exe_header)+(data_end-data_start)+511)>>9  ; Image size high bits, including header and relocations (none here), excluding .bss, rounded up.
+dw 0  ; Relocation count.
+dw 1  ; Paragraph (16 byte) count of header. Points to code_startseg.
+dw (bss_end-bss_start+15-(-((data_end-data_start)+(code_end-code_startseg))&15))>>4  ; Paragraph count of minimum required memory.
+dw 0xffff  ; Paragraph count of maximum required memory.
+dw (code_end-code_startseg)>>4  ; Stack segment (ss) base, will be same as ds. Low 4 bits are in vstart= of .data.
+code_startseg:
+dw (bss_end-bss_start)+(data_end-data_start) ; Stack pointer (sp).
+dw 0  ; No file checksum.
+dw code_start-code_startseg  ; Instruction pointer (ip): 8.
+dw 0  ; Code segment (cs) base.
+; We reuse the final 4 bytes of the .exe header (dw relocation_table_ofs,
+; overlay_number) for code.
+code_start:
+db 0x16  ; push ss
+db 0x1f  ; pop ds
+);
+$fullprog_data = q(
+code_end:
+; Fails with `error: TIMES value -... is negative` if code is too large (>~64 KiB).
+times -((code_end-code_startseg)>>16) db 0
+section .data align=1 vstart=((code_end-code_startseg)&15)
+data_start:
+);
+$fullprog_bss = q(
+data_end:
+section .bss align=1  ; vstart=0
+bss_start:
+);
+$fullprog_end = q(
+auto_stack:  ; Autodetect stack size to fill data segment to 65535 bytes.
+%define stack_size (65535-((auto_stack-bss_start)+(data_end-data_start)))
+times (stack_size-10)>>256 resb 0  ; Assert that stack size is at least 10.
+stack: resb stack_size
+bss_end:
+; Fails with `error: TIMES value -... is negative` if data is too large (>~64 KiB).
+times -(((bss_end-bss_start)+(data_end-data_start))>>16) db 0
+);
+  } elsif ($EXT eq "com") {
+# Based on https://github.com/pts/pts-nasm-fullprog/blob/master/fullprog_dosexe.inc.nasm
+$fullprog_code = q(
+section .text align=1 vstart=0x100  ; org 0x100
+code_start:
+);
+$fullprog_data = q(
+code_end:
+; Fails with `error: TIMES value -... is negative` if code is too large (>~64 KiB).
+times -((code_end-code_start+0x100)>>16) db 0
+section .data align=1 vstart=0x100+(code_end-code_start)  ; vfollows=.text is off by 2 bytes.
+data_start:
+);
+$fullprog_bss = q(
+data_end:
+section .bss align=1  ; vstart=0
+bss_start:
+);
+$fullprog_end = q(
+auto_stack:  ; Autodetect stack size to fill main segment to almost 65535 bytes.
+%define stack_size (65535-3-((auto_stack-bss_start)+(data_end-data_start)+(code_end-code_start+0x100)))
+times (stack_size-10)>>256 resb 0  ; Assert that stack size is at least 10.
+; This is fake, end of stack depends on DOS, typically sp==0xfffe or sp==0xfffc.
+stack: resb stack_size
+bss_end:
+call__fullprog_end:  ; Make fullprog_code without fullprog_end fail.
+; Fails with `error: TIMES value -... is negative` if data is too large (>~64 KiB).
+; +3 because some DOS systems set sp to 0xfffc instead of 0xffff
+; (http://www.fysnet.net/yourhelp.htm).
+times -(((bss_end-bss_start)+(data_end-data_start)+(code_end-code_start+0x100)+3)>>16) db 0
+);
+  } else {
+    die "$0: fatal: unknown EXT: $EXT\n";
+  }
+  print qq(bits 16\ncpu $NASMCPU\n);
+  print qq($fullprog_code\n);
   print qq(cld\npush es\npush ds\npop es\nmov di, bss_start\nmov cx, (stack-bss_start+1)>>1\nxor ax, ax\nrep stosw\npop es\n);
 
   my $entry_count = (defined($symbol_ofs{main_}) + defined($symbol_ofs{_main0_}));
@@ -326,21 +409,20 @@ OBJ2NASM_CODE='
     # `xor dx, dx` sets argv to NULL. ax is already 0 (for argc).
     # OpenWatcom wcc does not support non-constant initializers, so we can call
     # main now.
-    print "xor dx, dx\ncall main_\nmov ah, 0x4c  ; EXIT, exit code in al\nint 0x21\n%define fullprog_omit_code_exit\n";
+    print "xor dx, dx\ncall main_\nmov ah, 0x4c  ; EXIT, exit code in al\nint 0x21\n";
   } elsif (defined($symbol_ofs{_main0_})) {
     print qq(db 0xE8\ndw 0x0000+_main0_-\(\$+2\)  ; call _main0_\nmov ah, 0x4c  ; EXIT, exit code in al\nint 0x21\n);
   } else {
     die "$0: fatal: missing entry point (main function)\n";
   }
-  print qq(%define fullprog_omit_code_exit\n);
   dump_segment("_TEXT");
-  print qq(fullprog_data\n);
+  print qq($fullprog_data\n);
   dump_segment("CONST");  # String literals.
   dump_segment("CONST2");  # Other global consts.
   dump_segment("_DATA");
-  print qq(fullprog_bss\n);
+  print qq($fullprog_bss\n);
   dump_segment("_BSS");
-  print qq(fullprog_end\n);
+  print qq($fullprog_end\n);
 '
 export OBJ2NASM_CODE
 
@@ -374,7 +456,7 @@ if ! "$MYDIR"/ow2bin/wcc $Q $PL -bt=dos -ms -i="$MYDIR" -s -os -W -w4 -wx -we -w
 fi
 if test -z "$PL"; then
   #if ! "$MYDIR"/ow2bin/wdis -a -fi -i=@ "$SRCBASE.tmp.obj" >"$SRCBASE.tmp.wasm"; then die...; fi
-  if ! perl -e 'eval $ENV{OBJ2NASM_CODE}; die $@ if $@' <"$SRCBASE.tmp.obj" >"$SRCBASE.tmp.nasm"; then
+  if ! perl -e 'eval $ENV{OBJ2NASM_CODE}; die $@ if $@' -- "$EXT" "$NASMCPU" <"$SRCBASE.tmp.obj" >"$SRCBASE.tmp.nasm"; then
     test "$Q" || set +x  # Don't echo commands run anymore.
     echo "$0: fatal: obj2nasm failed" >&2
     exit 4
